# Generated by Django 5.2.3 on 2025-08-06 13:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/users/default_user.jpg', null=True, upload_to=users.models.generateImagePath),
        ),
    ]
